@echo off
echo ===============================================
echo    Android Development Environment Setup
echo ===============================================
echo.

echo Setting up system-wide Android environment...
echo.

REM Check if running as administrator
net session >nul 2>&1
if %errorLevel% neq 0 (
    echo WARNING: Not running as administrator!
    echo Some environment variables may not be set system-wide.
    echo Right-click and "Run as administrator" for full setup.
    echo.
)

REM Detect Android SDK path
set "DETECTED_SDK="
if exist "C:\Users\%USERNAME%\AppData\Local\Android\Sdk" (
    set "DETECTED_SDK=C:\Users\%USERNAME%\AppData\Local\Android\Sdk"
    echo Found Android SDK at: %DETECTED_SDK%
) else (
    echo Android SDK not found in default location.
    echo Please install Android Studio first.
    echo Download from: https://developer.android.com/studio
    echo.
)

REM Java detection
echo Checking Java installation...
java -version 2>nul
if %errorLevel% neq 0 (
    echo Java not found! Please install JDK 17 or later.
    echo Download from: https://adoptium.net/
    echo.
    set "JAVA_NEEDED=1"
) else (
    echo Java found in PATH.
    java -version
    echo.
)

if not "%DETECTED_SDK%"=="" (
    echo.
    echo ===============================================
    echo Setting Environment Variables...
    echo ===============================================
    
    REM Set ANDROID_HOME
    echo Setting ANDROID_HOME...
    setx ANDROID_HOME "%DETECTED_SDK%" >nul 2>&1
    if %errorLevel% equ 0 (
        echo ✓ ANDROID_HOME set to: %DETECTED_SDK%
    ) else (
        echo ✗ Failed to set ANDROID_HOME
    )
    
    REM Set ANDROID_SDK_ROOT (alternative name)
    echo Setting ANDROID_SDK_ROOT...
    setx ANDROID_SDK_ROOT "%DETECTED_SDK%" >nul 2>&1
    if %errorLevel% equ 0 (
        echo ✓ ANDROID_SDK_ROOT set to: %DETECTED_SDK%
    ) else (
        echo ✗ Failed to set ANDROID_SDK_ROOT
    )
    
    REM Add Android tools to PATH
    echo Adding Android tools to PATH...
    
    REM Get current PATH
    for /f "tokens=2*" %%a in ('reg query "HKCU\Environment" /v PATH 2^>nul') do set "CURRENT_PATH=%%b"
    if "%CURRENT_PATH%"=="" set "CURRENT_PATH="
    
    REM Add SDK tools to PATH if not already there
    echo %CURRENT_PATH% | find "%DETECTED_SDK%\platform-tools" >nul
    if %errorLevel% neq 0 (
        set "NEW_PATH=%CURRENT_PATH%;%DETECTED_SDK%\platform-tools;%DETECTED_SDK%\tools;%DETECTED_SDK%\tools\bin"
        setx PATH "%NEW_PATH%" >nul 2>&1
        if %errorLevel% equ 0 (
            echo ✓ Added Android SDK tools to PATH
        ) else (
            echo ✗ Failed to update PATH
        )
    ) else (
        echo ✓ Android SDK tools already in PATH
    )
    
    REM Create local.properties for this project
    echo.
    echo Creating local.properties file...
    (
        echo ## Android SDK Configuration for HelloWorldApp
        echo # Auto-generated by setup-environment.bat
        echo.
        echo # Android SDK Location
        echo sdk.dir=%DETECTED_SDK:\=\\%
        echo.
        echo # Build tools and platform tools are included automatically
        echo # NDK and CMake paths will be auto-detected if installed
    ) > local.properties
    
    if exist "local.properties" (
        echo ✓ Created local.properties with SDK path
    ) else (
        echo ✗ Failed to create local.properties
    )
    
    echo.
    echo ===============================================
    echo Environment Variables Summary:
    echo ===============================================
    echo ANDROID_HOME: %DETECTED_SDK%
    echo ANDROID_SDK_ROOT: %DETECTED_SDK%
    echo Platform Tools: %DETECTED_SDK%\platform-tools
    echo Build Tools: %DETECTED_SDK%\build-tools
    echo.
    
    echo ===============================================
    echo Verification Commands:
    echo ===============================================
    echo After restarting your command prompt, these should work:
    echo   adb version          (Android Debug Bridge)
    echo   avdmanager list avd  (List Android Virtual Devices)
    echo   sdkmanager --list    (SDK Manager)
    echo.
    
) else (
    echo ===============================================
    echo Manual Setup Required:
    echo ===============================================
    echo 1. Install Android Studio from: https://developer.android.com/studio
    echo 2. Open Android Studio and install SDK
    echo 3. Run this script again
    echo.
)

if "%JAVA_NEEDED%"=="1" (
    echo ===============================================
    echo Java Setup Required:
    echo ===============================================
    echo 1. Download JDK 17+ from: https://adoptium.net/
    echo 2. Install and make sure java is in PATH
    echo 3. Restart command prompt and run this script again
    echo.
)

echo ===============================================
echo Next Steps:
echo ===============================================
echo 1. Restart your command prompt/PowerShell
echo 2. Run: gradlew.bat assembleDebug
echo 3. Start Android Studio to create/manage AVDs
echo 4. Run: gradlew.bat installDebug
echo.

echo IMPORTANT: You may need to restart your computer
echo for all environment variables to take effect.
echo.

pause