# Android Development Environment Setup (PowerShell)
# Run this as Administrator for system-wide setup

Write-Host "===============================================" -ForegroundColor Cyan
Write-Host "    Android Development Environment Setup" -ForegroundColor Cyan
Write-Host "===============================================" -ForegroundColor Cyan
Write-Host ""

# Check if running as Administrator
$isAdmin = ([Security.Principal.WindowsPrincipal] [Security.Principal.WindowsIdentity]::GetCurrent()).IsInRole([Security.Principal.WindowsBuiltInRole] "Administrator")

if (-not $isAdmin) {
    Write-Host "WARNING: Not running as Administrator!" -ForegroundColor Yellow
    Write-Host "Some system-wide environment variables may not be set." -ForegroundColor Yellow
    Write-Host "Right-click PowerShell and 'Run as Administrator' for full setup." -ForegroundColor Yellow
    Write-Host ""
}

# Detect Android SDK
$androidSdkPaths = @(
    "$env:LOCALAPPDATA\Android\Sdk",
    "$env:USERPROFILE\AppData\Local\Android\Sdk",
    "C:\Android\Sdk",
    "$env:PROGRAMFILES\Android\Sdk",
    "${env:PROGRAMFILES(X86)}\Android\Sdk"
)

$detectedSdk = $null
foreach ($path in $androidSdkPaths) {
    if (Test-Path $path) {
        $detectedSdk = $path
        Write-Host "✓ Found Android SDK at: $detectedSdk" -ForegroundColor Green
        break
    }
}

if (-not $detectedSdk) {
    Write-Host "✗ Android SDK not found!" -ForegroundColor Red
    Write-Host "Please install Android Studio first:" -ForegroundColor Yellow
    Write-Host "https://developer.android.com/studio" -ForegroundColor Blue
    Write-Host ""
    Read-Host "Press Enter to continue"
    exit 1
}

# Check Java
Write-Host "Checking Java installation..." -ForegroundColor Cyan
try {
    $javaVersion = java -version 2>&1
    Write-Host "✓ Java found:" -ForegroundColor Green
    Write-Host $javaVersion[0] -ForegroundColor Gray
} catch {
    Write-Host "✗ Java not found!" -ForegroundColor Red
    Write-Host "Please install JDK 17+ from: https://adoptium.net/" -ForegroundColor Yellow
    Write-Host ""
}

Write-Host ""
Write-Host "===============================================" -ForegroundColor Cyan
Write-Host "Setting Environment Variables..." -ForegroundColor Cyan
Write-Host "===============================================" -ForegroundColor Cyan

try {
    # Set ANDROID_HOME
    [Environment]::SetEnvironmentVariable("ANDROID_HOME", $detectedSdk, "User")
    Write-Host "✓ Set ANDROID_HOME to: $detectedSdk" -ForegroundColor Green
    
    # Set ANDROID_SDK_ROOT
    [Environment]::SetEnvironmentVariable("ANDROID_SDK_ROOT", $detectedSdk, "User")
    Write-Host "✓ Set ANDROID_SDK_ROOT to: $detectedSdk" -ForegroundColor Green
    
    # Update PATH
    $currentPath = [Environment]::GetEnvironmentVariable("PATH", "User")
    $platformTools = "$detectedSdk\platform-tools"
    $tools = "$detectedSdk\tools"
    $toolsBin = "$detectedSdk\tools\bin"
    
    $pathsToAdd = @($platformTools, $tools, $toolsBin)
    $pathUpdated = $false
    
    foreach ($pathToAdd in $pathsToAdd) {
        if ($currentPath -notlike "*$pathToAdd*") {
            $currentPath += ";$pathToAdd"
            $pathUpdated = $true
        }
    }
    
    if ($pathUpdated) {
        [Environment]::SetEnvironmentVariable("PATH", $currentPath, "User")
        Write-Host "✓ Added Android SDK tools to PATH" -ForegroundColor Green
    } else {
        Write-Host "✓ Android SDK tools already in PATH" -ForegroundColor Green
    }
    
} catch {
    Write-Host "✗ Failed to set environment variables: $($_.Exception.Message)" -ForegroundColor Red
}

# Create local.properties
Write-Host ""
Write-Host "Creating local.properties file..." -ForegroundColor Cyan
$localPropertiesContent = @"
## Android SDK Configuration for HelloWorldApp
# Auto-generated by setup-environment.ps1

# Android SDK Location
sdk.dir=$($detectedSdk -replace '\\', '\\')

# Build tools and platform tools are included automatically
# NDK and CMake paths will be auto-detected if installed
"@

try {
    $localPropertiesContent | Out-File -FilePath "local.properties" -Encoding UTF8
    Write-Host "✓ Created local.properties with SDK path" -ForegroundColor Green
} catch {
    Write-Host "✗ Failed to create local.properties: $($_.Exception.Message)" -ForegroundColor Red
}

Write-Host ""
Write-Host "===============================================" -ForegroundColor Cyan
Write-Host "Environment Setup Complete!" -ForegroundColor Cyan
Write-Host "===============================================" -ForegroundColor Cyan
Write-Host "ANDROID_HOME: $detectedSdk" -ForegroundColor Gray
Write-Host "Platform Tools: $detectedSdk\platform-tools" -ForegroundColor Gray
Write-Host "Build Tools: $detectedSdk\build-tools" -ForegroundColor Gray
Write-Host ""

Write-Host "===============================================" -ForegroundColor Cyan
Write-Host "Next Steps:" -ForegroundColor Cyan
Write-Host "===============================================" -ForegroundColor Cyan
Write-Host "1. Restart PowerShell/Command Prompt" -ForegroundColor Yellow
Write-Host "2. Run: .\gradlew.bat assembleDebug" -ForegroundColor Yellow
Write-Host "3. Start Android Studio to manage AVDs" -ForegroundColor Yellow
Write-Host "4. Run: .\gradlew.bat installDebug" -ForegroundColor Yellow
Write-Host ""

Write-Host "Verification commands (after restart):" -ForegroundColor Cyan
Write-Host "  adb version" -ForegroundColor Gray
Write-Host "  avdmanager list avd" -ForegroundColor Gray
Write-Host "  sdkmanager --list" -ForegroundColor Gray
Write-Host ""

Read-Host "Press Enter to continue"